version: '3'
services:
  src-trac-web-app:
    restart: always
    env_file: .env
    build: .
    ports:
      - "8001:8001"
#     networks:
#       - db_network
#       - web_network
      
# networks:
#   db_network:
#     driver: bridge
#   web_network:
#     driver: bridge